### PR TITLE
Fast bq download pr

### PR DESCRIPTION
**Pull request by peteratemarsys**
- Adding bqr_download_query method that exports a GBQ query result to CloudStorage and then downloads it to a local folder
- Adding documentation and extending dependencies

### CODE REVIEW

**Comment by peteratemarsys** [comment]
Hi @MarkEdmondson1234!
After the PR we realised a few things. Could you please confirm if you agree?

1. We put a few new dependencies into the `Suggests` part of the DESCRIPTION file but we realised that since our new function depends on it we might need to move it to the `Imports` part.
2. We haven't added new tests. We would do it next week.
3. The build is currently failing due to a warning, saying
`Undocumented arguments in documentation object 'bqr_get_global_dataset'
  ‘...’`. We believe that this is not something on our end.

Also, looking forward to any feedback.

Thanks,
Peter

**Comment by MarkEdmondson1234** [comment]
Thanks @peteratmarsys !

1. I prefer as little packages in `Imports` as possible, (may even move some out) so `Suggests` is good, especially as only one function needing them.  To help uses this function helps give them a prompt to install the missing package, e.g.

```r
if (!requireNamespace("bigQueryR", quietly = TRUE)) {
    stop("bigQueryR needed for this function to work. Please install it via install.packages('bigQueryR')",
         call. = FALSE)
}
```

2. Thanks, API tests that need auth are tricky so for now if you just make them so they work locally, I can adpat them to use mocking or similar in future (a todo for me)
3. I made some changes recently, this may be me, sorry :)

It looks super useful, I will test it out myself and give more feedback as soon as I get the chance (bit loaded at the moment but will try by end of month)

**Comment by MarkEdmondson1234** [comment]
`stringr` is a surprisingly big dependency too, so if the same can be done using base R `gsub()` etc. that would be better.

**Comment by MarkEdmondson1234** [comment]
Great!  I'll merge and maybe tweak it a bit before publishing to CRAN, in particular removing purrr if possible but minor things!

**Comment by peteratemarsys** [comment]
Great, thank you!

**Pull request merged**
